//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailId { get; set; }
        public string ProductName { get; set; }
        public Nullable<short> ProductSaleQuantity { get; set; }
        public Nullable<decimal> ProductUnitPrice { get; set; }
        public Nullable<decimal> ProductTotalPrice { get; set; }
        public Nullable<int> Invoice { get; set; }
    
        public virtual Invoice Invoice1 { get; set; }
    }
}
