//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTrace
    {
        public int ProductTraceId { get; set; }
        public Nullable<int> Product { get; set; }
        public string ProductConditon { get; set; }
        public Nullable<int> ProductTraceDate { get; set; }
        public string ProductTraceCode { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
