// <auto-generated />
namespace TeknikServis.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initlaptop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initlaptop));
        
        string IMigrationMetadata.Id
        {
            get { return "202411272204200_init-laptop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
