// <auto-generated />
namespace TeknikServis.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ptracedbupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ptracedbupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202412030902231_ptrace-db-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
