// <auto-generated />
namespace TeknikServis.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initPC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initPC));
        
        string IMigrationMetadata.Id
        {
            get { return "202411291910228_init-PC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
